#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_LINUX_FLAVOURS="amd64"
		_SOURCE="false"
		;;

	i386)
		_LINUX_FLAVOURS="486 686-pae"
		_SOURCE="true"
		;;
esac

lb config noauto \
        -a amd64 \
        -d wheezy \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--debian-installer live \
	--linux-flavours "${_LINUX_FLAVOURS}" \
	--linux-packages "linux-image linux-headers" \
	--source "${_SOURCE}" \
        --archive-areas "main contrib non-free" \
        --bootappend-live "\
boot=live \
config \
persistence \
persistence-encryption=luks,none \
persistent=cryptsetup \
quickreboot \
username=pcarrier \
hostname=shoe" \
"${@}"


# todo:
#
# (boot param) live-config.locales=it_IT live-config.timezone=Europe/Rome live-config.keyboard-layouts=it \
# --apt-recommends true \
# --linux-packages linux-image-3.7-trunk \
#  mirror="http://ftp.debian.org/debian/";  
#   security_mirror="http://ftp.debian.org/debian-security/"; 
#   --mirror-bootstrap "${mirror}" \
#   --mirror-binary "${mirror}" \
#   --mirror-chroot-security "${security_mirror}" \
#   --mirror-binary-security "${security_mirror}" \
